protected/controllers/EsaiController.php
<?php

class EsaiController extends UniversalContestantController
{
    /**
     * Creates a new model.
     */
    public function actionPendaftaran()
    {
        parent::allRegistration('paper');
    }

    /**
     * Deletes a particular model.
     * If deletion is successful, the browser will be redirected to the 'admin' page.
     * @param integer $id the ID of the model to be deleted
     */
    public function actionDelete($id)
    {
        parent::allDelete($this->loadModel($id));
    }

    /**
     * Show Paper Contestant Profile from Admin
     */
    public function actionView($id)
    {
        $this->layout = '//layouts/main3';
        parent::afterProfile('paper', $this->loadModel($id));
    }

    /**
     * Show Paper Contest Description
     */
    public function actionIndex()
    {
        if((Yii::app()->user->isGuest) || (Yii::app()->user->type != 3)) $model = null;
        else $model = $this->loadModel(Yii::app()->user->id);
        parent::afterIndex('paper', $model);
    }

    /**
     * Show Paper Contestant Profile
     */
    public function actionProfil()
    {
        if(Yii::app()->user->isGuest) $model = null;
        else $model = $this->loadModel(Yii::app()->user->id);
        parent::afterProfile('paper', $model);
    }

    /**
     * Show Paper Contestant Payment upload page
     */
    public function actionPayment()
    {
        parent::allPayment('paper');
    }

    /**
     * Show Paper Contestant Problem upload page
     */
    public function actionMasalah()
    {
        parent::allProblem('paper');
    }

    /**
     * Manages all models.
     */
    public function actionAdmin()
    {
        parent::allAdmin('paper');
    }

    /**
     * Verify Paper Contestant Payment
     */
    public function actionPaid($id)
    {
        parent::allVerify($id, 0);
    }

    /**
     * Retry Verify University Modeling Contestant Payment
     */
    public function actionRepaid($id)
    {
        if(isset($_GET['mirzaganteng']) && ($_GET['mirzaganteng'] == 'true')) parent::retryVerify($id, 0);
        else echo '<div>Katakan Mirza Ganteng 3x, lalu klik OK!</div><div><button>OK</button>';
    }

    /**
     * Verify Paper Contestant Complete Data
     */
    public function actionComplete($id)
    {
        parent::allVerify($id, 1);
    }

    /**
     * Show University Modeling Contestant Problem upload page
     */
    public function actionPengumpulan()
    {
        if( (!Yii::app()->user->isGuest) && (Yii::app()->user->type==3))
        {
            $model = Problem::model()->findByAttributes(array('contestant_id' => Yii::app()->user->id));
            if($model == null){
                $model                = new Problem();
                $model->contestant_id = Yii::app()->user->id;
            }

            if(!empty($_FILES) && (
            ($_FILES['file']['type'] == 'application/pdf') ||
            ($_FILES['file']['type'] == 'application/x-pdf') ||
            ($_FILES['file']['type'] == 'application/msword') ||
            ($_FILES['file']['type'] == 'application/vnd.openxmlformats-officedocument.wordprocessingml.document')
            )){
                $filename = $_FILES['file']['name'];
                if((strlen($filename)!=0) && (file_exists('upload/'.$filename))) unlink('upload/'.$filename);
                move_uploaded_file($_FILES['file']['tmp_name'], 'upload/'.$filename);
                if((strlen($filename)!=0) && (file_exists('backup/'.$filename))) unlink('backup/'.$filename);
                copy('upload/'.$filename, 'backup/'.$filename);
                $model->file_name = $filename;
                if($model->save()) Yii::app()->user->setFlash('success', 'Berkas berhasil diunggah');
            }

            $this->render('submit', array(
                'model'  => $model,
            ));
        }
        else throw new CHttpException(404,'The requested page does not exist.');
    }

    /**
     * Returns the data model based on the primary key given in the GET variable.
     * If the data model is not found, an HTTP exception will be raised.
     * @param integer $id the ID of the model to be loaded
     * @return paper the loaded model
     * @throws CHttpException
     */
    public function loadModel($id)
    {
        $model=Paper::model()->findByPk($id);
        if($model===null)
            throw new CHttpException(404,'The requested page does not exist.');
        return $model;
    }

    /**
     * Performs the AJAX validation.
     * @param paper $model the model to be validated
     */
    protected function performAjaxValidation($model)
    {
        if(isset($_POST['ajax']) && $_POST['ajax']==='paper-form')
        {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
    }

    /**
     * Activate registration
     */
    public function actionStart()
    {
        parent::regButton('paper', 'start');
    }

    /**
     * Disable registration
     */
    public function actionStop()
    {
        parent::regButton('paper', 'stop');
    }
}

protected/controllers/HomeController.php
<?php

class HomeController extends Controller
{
    /**
     * Declares class-based actions.
     */
    public function actions()
    {
        return array(
            // captcha action renders the CAPTCHA image displayed on the contact page
            'captcha'=>array(
                'class'=>'CCaptchaAction',
                'backColor'=>0xFFFFFF,
            ),
            // page action renders "static" pages stored under 'protected/views/site/pages'
            // They can be accessed via: index.php?r=site/page&view=FileName
            'page'=>array(
                'class'=>'CViewAction',
            ),
        );
    }

    /**
     * @return array action filters
     */
    public function filters()
    {
        return array(
            'accessControl', // perform access control for CRUD operations
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules()
    {
        return array(
            array('allow',
                'actions'=>array('login', 'logout', 'index', 'sync', 'error'),
                'users'=>array('*'),
            ),
            array('allow',
                'actions'=>array('index', 'error'),
                'users'=>array('@'),
            ),
            array('allow',
                'actions'=>array('admin', 'index', 'error'),
                'users'=>array('admin'),
            ),
            array('deny',  // deny all users
                'users'=>array('*'),
            ),
        );
    }

    /**
     * This is the default 'index' action that is invoked
     * when an action is not explicitly requested by users.
     */
//    public function actionIndex()
//    {
        // renders the view file 'protected/views/site/index.php'
        // using the default layout 'protected/views/layouts/main.php'
//        $this->render('index');
//    }

    /**
     * This is the action to handle external exceptions.
     */
    public function actionError()
    {
        if($error=Yii::app()->errorHandler->error)
        {
            if(Yii::app()->request->isAjaxRequest)
                echo $error['message'];
            else
                $this->render('error', $error);
        }
    }

    /**
     * Displays the contact page
     */
    public function actionContact()
    {
        $model=new ContactForm;
        if(isset($_POST['ContactForm']))
        {
            $model->attributes=$_POST['ContactForm'];
            if($model->validate())
            {
                $name='=?UTF-8?B?'.base64_encode($model->name).'?=';
                $subject='=?UTF-8?B?'.base64_encode($model->subject).'?=';
                $headers="From: $name <{$model->email}>\r\n".
                    "Reply-To: {$model->email}\r\n".
                    "MIME-Version: 1.0\r\n".
                    "Content-type: text/plain; charset=UTF-8";

                mail(Yii::app()->params['adminEmail'],$subject,$model->body,$headers);
                Yii::app()->user->setFlash('contact','Thank you for contacting us. We will respond to you as soon as possible.');
                $this->refresh();
            }
        }
        $this->render('contact',array('model'=>$model));
    }

    /**
     * Displays the login page
     */
    public function actionIndex()
    {
        $model=new LoginForm;

        // if it is ajax validation request
        if(isset($_POST['ajax']) && $_POST['ajax']==='login-form')
        {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }

        // collect user input data
        if(isset($_POST['LoginForm']))
        {
            $model->attributes=$_POST['LoginForm'];
            // validate user input and redirect to the previous page if valid
            if($model->validate() && $model->login())
                switch(Yii::app()->user->type)
                {
                    case -1 : $this->redirect(array("/tes"));                  break;
                    case 0  : $this->redirect(array("home/admin"));            break;
                    case 1  : $this->redirect(array("/pemodelan_siswa"));      break;
                    case 2  : $this->redirect(array("/pemodelan_mahasiswa"));  break;
                    case 3  : $this->redirect(array("/esai"));                 break;
                    case 4  : $this->redirect(array("/seminar_nasional"));     break;
                    default : $this->redirect(array("/"));
                }
        }
        // display the login form
        $this->render('login',array('model'=>$model));
    }

    /**
     * Show admin homepage.
     */
    public function actionAdmin()
    {
        $this->layout = 'main3';

        $criteria = array(
            'condition' => 'topic_id > 3 AND topic_id < 6',
        );
        $topic_school = Topic::model()->findAll($criteria);

        $topic_university = array();
        $criteria = array(
            'condition' => 'topic_id < 4',
        );
        $topics = Topic::model()->findAll($criteria);
        foreach($topics as $topic)
            array_push($topic_university, array(
                'topic' => $topic,
                'amount' => TopicChoice::model()->countByAttributes(array('topic_id' => $topic->topic_id)),
            ));

        $choosens_school = array();
        $criteria = array(
            'condition' => 'topic_id > 3 AND topic_id < 6',
            'order'     => 'contestant_id',
        );
        $topic_choice = TopicChoice::model()->findAll($criteria);
        foreach($topic_choice as $tc){
            $contestant = University::model()->findByPk($tc->contestant_id);
            $contestant = ($contestant == null) ? $contestant = Contestant::model()->findByPk($tc->contestant_id)->contestant_username : 'Tim ' . $contestant->contestant_team_name;
            array_push($choosens_school, array(
                'id' => $tc->contestant_id,
                'contestant' => $contestant,
                'topic' => Topic::model()->findByPk($tc->topic_id)->topic_title,
            ));
        }

        $choosens_university = array();
        $criteria = array(
            'condition' => 'topic_id < 4',
            'order'     => 'contestant_id',
        );
        $topic_choice = TopicChoice::model()->findAll($criteria);
        foreach($topic_choice as $tc){
            $contestant = University::model()->findByPk($tc->contestant_id);
            $contestant = ($contestant == null) ? $contestant = Contestant::model()->findByPk($tc->contestant_id)->contestant_username : 'Tim ' . $contestant->contestant_team_name;
            array_push($choosens_university, array(
                'id' => $tc->contestant_id,
                'contestant' => $contestant,
                'topic' => Topic::model()->findByPk($tc->topic_id)->topic_title,
            ));
        }

        $this->render('admin',array(
            'topic_school'        => $topic_school,
            'topic_university'    => $topic_university,
            'choosens_school'     => $choosens_school,
            'choosens_university' => $choosens_university,
        ));
    }

    /**
     * Generate School Contestant data for sync
     */
    public function actionSync()
    {
        $criteria = array(
            'condition' => 'contestant_type = 1 AND contestant_status = 2',
        );
        $model = Contestant::model()->findAll($criteria);
        $this->renderPartial('sync',array(
            'model'=>$model
        ));
    }

    /**
     * Logs out the current user and redirect to homepage.
     */
    public function actionLogout()
    {
        Yii::app()->user->logout();
        $this->redirect(Yii::app()->homeUrl);
    }
}

protected/controllers/TesController.php
<?php

class TesController extends Controller
{
    /**
     * @var string the default layout for the views. Defaults to '//layouts/main4', meaning
     * using two-column layout. See 'protected/views/layouts/main4.php'.
     */
    public $layout='//layouts/main4';

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules()
    {
        return array(
            array('allow',
                'actions'=>array('topik', 'penyisihan', 'index'),
                'users'=>array('@'),
            ),
            array('deny',  // deny all users
                'users'=>array('*'),
            ),
        );
    }

    /**
     * Index
     */
    public function actionIndex()
    {
        if(Yii::app()->user->id > 50) $this->render('preliminary1');
        else $this->render('index');
    }

    public function actionPenyisihan()
    {
        if($_POST != null) {
            $this->render('preliminary2', array(
                'start' => 11,
            ));
        }
        else {
            $this->render('preliminary2', array(
                'start' => 1,
            ));
        }
    }

    public function actionTopik()
    {
        $choice = TopicChoice::model()->find(array(
            'condition'=>'contestant_id=:id',
            'params'=>array(':id'=>Yii::app()->user->id),
        ));
        $criteria = array(
            'condition' => 'topic_id > 3 AND topic_id < 6',
        );
        $topics = Topic::model()->findAll($criteria);

        $this->render('topic', array(
            'topics'=>$topics,
            'choice'=>$choice,
        ));
    }

    /**
     * Upload Motivation Letter
     */
    public function actionMotivation_letter()
    {
        if( (!Yii::app()->user->isGuest) && (Yii::app()->user->type==-1))
        {
            if(!empty($_FILES)){
                Yii::app()->user->setFlash('warning', 'Laman ini hanya untuk uji coba. Berkas yang Anda unggah tidak akan disimpan');
            }
            $this->render('letter');
        }
        else throw new CHttpException(404,'The requested page does not exist.');
    }

    /**
     * Show University Modeling Contestant Problem upload page
     */
    public function actionMasalah()
    {
        $model = Topic::model()->findAll();
        $this->render('problem', array(
            'model'=>$model,
        ));
    }

    public function actionPengumpulan()
    {
        if( (!Yii::app()->user->isGuest) && (Yii::app()->user->type==-1))
        {
            $topic_choice = TopicChoice::model()->findByAttributes(array('contestant_id'=>Yii::app()->user->id));
            if($topic_choice == null) $topic = new Topic();
            else $topic = Topic::model()->findByPk($topic_choice->topic_id);

            //$filename = Contestant::model()->findByPk(Yii::app()->user->id)->contestant_username.'_'.$topic_choice->topic_id.'_Laporan.pdf';
            $filename = "";
            $model = Problem::model()->findByAttributes(array('contestant_id' => Yii::app()->user->id));
            if($model == null){
                $model                = new Problem();
                $model->contestant_id = Yii::app()->user->id;
            }

            if(!empty($_FILES)){
                if((strlen($filename)!=0) && (file_exists('upload/'.$filename))) unlink('upload/'.$filename);
                else $model->file_name = $filename;
                move_uploaded_file($_FILES['file']['tmp_name'], 'upload/'.$filename);
                if((strlen($filename)!=0) && (file_exists('backup/'.$filename))) unlink('backup/'.$filename);
                copy('upload/'.$filename, 'backup/'.$filename);
                if($model->save()) Yii::app()->user->setFlash('success', 'Berkas berhasil diunggah dengan nama '.$filename);
            }

            $this->render('submit', array(
                'problem' => $topic,
                'model'  => $model,
            ));
        }
        else throw new CHttpException(404,'The requested page does not exist.');
    }
}

protected/views/layouts/blank.php
<?php
/* @var $this Controller */
?>
<!DOCTYPE html>
<html>
	<head>
		<link rel="stylesheet" href="<?php echo Yii::app()->request->baseUrl; ?>/css/bootstrap.min.css">
		<link rel="stylesheet" href="<?php echo Yii::app()->request->baseUrl; ?>/css/bootstrap-responsive.min.css">
		<link rel="stylesheet" href="<?php echo Yii::app()->request->baseUrl; ?>/css/foundation.css">
		<link rel="stylesheet" href="<?php echo Yii::app()->request->baseUrl; ?>/css/app.css">
	</head>
	<body class="page page-template page-template-tmp-archive-left-img-php siteorigin-panels wpb-js-composer js-comp-ver-3.6.7 vc_responsive" style="">
		<div id="change_wrap_div">
			<section id="layout">
				<div class="row"><?php echo $content; ?></div>
			</section>
		</div>
		<script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl; ?>/js/bootstrap.min.js"></script>
	</body>
</html>

protected/views/layouts/main.php
<?php
/* @var $this Controller */
$home = Yii::app()->createUrl("/");
switch(Yii::app()->controller->id){
    case 'tentang'                : $page = ' - Tentang';  break;
    case 'berita'                 : $page = ' - Berita';   break;
    case 'pemodelan_siswa'        : $page = ' - Acara';    break;
    case 'pemodelan_mahasiswa'    : $page = ' - Acara';    break;
    case 'esai'                   : $page = ' - Acara';    break;
    case 'pameran_karya'          : $page = ' - Acara';    break;
    case 'seminar_nasional'       : $page = ' - Acara';    break;
    case 'kontak'                 : $page = ' - Kontak';   break;
    default                       : $page = '';
}
if((Yii::app()->controller->id=='home')&&(Yii::app()->controller->action->id=='error')) $page = ' - Error';
?>
<!DOCTYPE html>
<html class=" js no-touch svg inlinesvg svgclippaths no-ie8compat" lang="en-US" style="overflow: hidden;">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta name="description" content="Mathematical Challenge Festival (MCF) Institut Teknologi Bandung merupakan acara dwitahunan yang diselenggarakan oleh Himpunan Mahasiswa Matematika (HIMATIKA) ITB sejak tahun 2002. Dalam perkembangannya, MCF ITB telah diadakan sebanyak lima kali.">
        <meta name="keywords" content="MCF, MMC, MCF-MMC, MCF - MMC, MCF6, MCF 6, MCF 6 ITB, MCF ITB, MMC ITB, MCF-MMC ITB, MCF - MMC ITB, MCF 2014, MMC 2014, MCF-MMC 2014, MCF - MMC 2014, MCF ITB 2014, MMC ITB 2014, MCF-MMC ITB 2014, MCF - MMC ITB 2014, Mathematical Challenge Festival, Mathematical Challenge Festival ITB">
        <meta property="og:title" content="MCF-MMC ITB 2014">
        <meta property="og:url" content="http://www.math.itb.ac.id/mcf-mmc/">
        <meta property="og:image" content="http://www.math.itb.ac.id/mcf-mmc/img/logo.jpg">
        <title>MCF-MMC ITB 2014<?php echo $page; ?></title>
        <link rel="shortcut icon" href="<?php echo Yii::app()->request->baseUrl.'/img/'.(rand(0,1)==1?'mcf':'mmc').'.ico'; ?>">
        <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans%3A400italic%2C700italic%2C400%2C700&subset=latin%2Clatin-ext&ver=3.6.1">
        <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Source+Sans+Pro%3A300%2C400%2C600%2C700%2C300italic%2C400italic%2C600italic%2C700italic&subset=latin%2Clatin-ext&ver=3.6.1">
        <link rel="stylesheet" href="<?php echo Yii::app()->request->baseUrl; ?>/css/bootstrap.min.css">
        <link rel="stylesheet" href="<?php echo Yii::app()->request->baseUrl; ?>/css/icon-font-style.css?ver=3.6.1">
        <link rel="stylesheet" href="<?php echo Yii::app()->request->baseUrl; ?>/css/foundation.css">
        <link rel="stylesheet" href="<?php echo Yii::app()->request->baseUrl; ?>/css/app.css">
        <link rel="stylesheet" href="<?php echo Yii::app()->request->baseUrl; ?>/css/options.css">
        <script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl; ?>/js/jsapi"></script>
        <script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl; ?>/js/jquery.js?ver=1.10.2"></script>
        <script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl; ?>/js/jquery.tipsy.js"></script>
        <script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl; ?>/js/jquery.carouFredSel-6.2.1.js"></script>
        <script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl; ?>/js/bootstrap.min.js"></script>
    </head>
    <body class="page page-template page-template-tmp-archive-left-img-php siteorigin-panels wpb-js-composer js-comp-ver-3.6.7 vc_responsive" style="">
        <div id="change_wrap_div">
            <section id="header" class="horizontal">
                <div class="row">
                    <div class="twelve columns">
                        <div id="logo"><a href="<?php echo $home; ?>" title="Halaman Utama"><img src="<?php echo Yii::app()->request->baseUrl; ?>/img/Untitled-21.png" alt="MCF-MMC 2014"></a></div>
                        <div id="header-login-form">
                            <?php if(Yii::app()->user->isGuest): ?>
                            <form class="form-inline" action="<?php echo Yii::app()->createUrl("/"); ?>/" method="post" role="form">
                                <div class="form-group">
                                    <label class="sr-only" for="inputUsername">Username</label>
                                    <input type="text" class="form-control" id="LoginForm_username" name="LoginForm[username]" placeholder="Username">
                                </div>
                                <div class="form-group">
                                    <label class="sr-only" for="inputPassword">Password</label>
                                    <input type="password" class="form-control" id="LoginForm_password" name="LoginForm[password]" placeholder="Password">
                                </div>
                                <input class="btn btn-default btn-sm" type="submit" value="Masuk">
                            </form>

                            <?php else: ?>
                            <a id="logout" href="<?php echo Yii::app()->createUrl("/home/logout"); ?>">Keluar</a>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
                <div class="header-navi-wrap crum_start_animation">
                    <div class="header-navi">
                        <div class="header-navi-inner">
                            <nav id="top-menu" class="fake">
                                <ul id="menu-top" class="menu">
                                <?php require $_SERVER['DOCUMENT_ROOT'].Yii::app()->baseUrl.'/protected/views/layouts/menu.php'; ?>
                                </ul>
                            </nav>
                            <div class="cl"></div>
                        </div>
                    </div>
                </div>
                <div class="droped-navi" style="top: -60px; opacity: 0;">
                    <div class="droped-navi-inner">
                        <div class="small-logo">
                            <a href="<?php echo $home; ?>"><img src="<?php echo Yii::app()->request->baseUrl; ?>/img/Untitled-21.png" alt="MCF-MMC 2014" title="Halaman Utama"></a>
                        </div>
                        <nav id="drop-top-menu" class="fake">
                            <ul id="menu-top-1" class="menu">
                                <?php require $_SERVER['DOCUMENT_ROOT'].Yii::app()->baseUrl.'/protected/views/layouts/menu.php'; ?>
                            </ul>
                        </nav>
                    </div>
                </div>
            </section>

            <?php if(Yii::app()->controller->id!='home') : ?>
            <div id="stuning-header">
                <div class="row">
                    <div class="twelve columns">
                        <div id="page-title">
                            <a href="javascript:history.back()" class="back"></a>
                            <div class="page-title-inner">
                                <h1 class="page-title">
                                <?php
                                    $title = (Yii::app()->controller->action->id=="pendaftaran") ? "Pendaftaran" : Yii::app()->controller->id;
                                    echo ucwords(str_replace("_", " ", $title));
                                ?>
                                </h1>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <?php endif; ?>

            <section id="layout">
                <div class="row"><?php echo $content; ?></div>
            </section>

            <div class="push"></div>
        </div>

        <section id="sub-footer">
            <div class="row">
                <div class="six mobile-two columns">&copy Panitia MCF - MMC ITB 2014</div>
                <div class="six mobile-two columns right">#IndonesiaBermatematika</div>
            </div>
            <a href="#" id="linkTop" class="backtotop hidden"></a>
        </section>
        <script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl; ?>/js/foundation.min.js"></script>
        <script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl; ?>/js/jquery.nicescroll.min.js"></script>
        <script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl; ?>/js/jquery.nicescroll.plus.js"></script>
        <script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl; ?>/js/app.js"></script>
        <script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl; ?>/js/bootstrap.min.js"></script>
        <div id="ascrail2000" class="nicescroll-rails" style="width: 10px; z-index: 9999; cursor: default; position: fixed; top: 0px; height: 100%; right: 0px; opacity: 0.8; border-top-left-radius: 10px; border-top-right-radius: 10px; border-bottom-right-radius: 10px; border-bottom-left-radius: 10px;">
            <div style="position: relative; top: 0px; float: right; width: 4px; height: 296px; background-color: rgb(97, 107, 116); border: 0px; background-clip: padding-box; border-top-left-radius: 10px; border-top-right-radius: 10px; border-bottom-right-radius: 10px; border-bottom-left-radius: 10px;"></div>
        </div>
        <div id="ascrail2000-hr" class="nicescroll-rails" style="height: 10px; z-index: 9999; position: fixed; left: 0px; width: 100%; bottom: 0px; opacity: 0.8; cursor: default; display: none;">
            <div style="position: relative; top: 0px; height: 10px; width: 1366px; background-color: rgb(97, 107, 116); border: 0px; background-clip: padding-box; border-top-left-radius: 10px; border-top-right-radius: 10px; border-bottom-right-radius: 10px; border-bottom-left-radius: 10px;"></div>
        </div>
    </body>
</html>

protected/views/layouts/menu3.php
									<li <?php echo (Yii::app()->controller->id=='pemodelan_siswa') ? "class=\"current-menu-item\"" : ""; ?>>
										<span class="menu-item-wrap linecon-pencil">
											<a title="Pemodelan Siswa" href="<?php echo Yii::app()->createUrl('pemodelan_siswa/admin'); ?>">
												<span class="link-text">Pemodelan Siswa</span>
												<span class="link-desc"></span>
											</a>
										</span>
									</li>
									<li <?php echo (Yii::app()->controller->id=='pemodelan_mahasiswa') ? "class=\"current-menu-item\"" : ""; ?>>
										<span class="menu-item-wrap linecon-graduation-cap">
											<a title="Pemodelan Mahasiswa" href="<?php echo Yii::app()->createUrl('pemodelan_mahasiswa/admin'); ?>">
												<span class="link-text">Pemodelan Mahasiswa</span>
												<span class="link-desc"></span>
											</a>
										</span>
									</li>
									<li <?php echo (Yii::app()->controller->id=='esai') ? "class=\"current-menu-item\"" : ""; ?>>
										<span class="menu-item-wrap linecon-attach">
											<a title="Esai" href="<?php echo Yii::app()->createUrl('esai/admin'); ?>">
												<span class="link-text">Esai</span>
												<span class="link-desc"></span>
											</a>
										</span>
									</li>
									<li <?php echo (Yii::app()->controller->id=='seminar_nasional') ? "class=\"current-menu-item\"" : ""; ?>>
										<span class="menu-item-wrap linecon-globe">
											<a title="Seminar Nasional" href="<?php echo Yii::app()->createUrl('seminar_nasional/admin'); ?>">
												<span class="link-text">Seminar Nasional</span>
												<span class="link-desc"></span>
											</a>
										</span>
									</li>

protected/views/layouts/menu4.php
									<li <?php echo (Yii::app()->controller->action->id=='index') ? "class=\"current-menu-item\"" : ""; ?>>
										<span class="menu-item-wrap linecon-sound">
											<a title="Pengumuman Lomba" href="<?php echo Yii::app()->createUrl(Yii::app()->controller->id); ?>">
												<span class="link-text">Pengumuman</span>
												<span class="link-desc">Pengumuman Lomba</span>
											</a>
										</span>
									</li>
									<li <?php echo (Yii::app()->controller->action->id=='masalah') ? "class=\"current-menu-item\"" : ""; ?>>
										<span class="menu-item-wrap linecon-search">
											<a title="Soal & Pengumpulan Jawaban" href="<?php echo Yii::app()->getController()->createUrl("masalah"); ?>">
												<span class="link-text">Masalah</span>
												<span class="link-desc">Pilihan Topik Masalah</span>
											</a>
										</span>
									</li>
									<li <?php echo (Yii::app()->controller->action->id=='topik') ? "class=\"current-menu-item\"" : ""; ?>>
										<span class="menu-item-wrap linecon-tag">
											<a title="Topik" href="<?php echo Yii::app()->createUrl('tes/topik'); ?>">
												<span class="link-text">Topik</span>
												<span class="link-desc">Pilih Topik Pemodelan</span>
											</a>
										</span>
									</li>
									<li <?php echo (Yii::app()->controller->action->id=='pengumpulan') ? "class=\"current-menu-item\"" : ""; ?>>
										<span class="menu-item-wrap linecon-attach">
											<a title="Unggah Motivation Letter" href="<?php echo Yii::app()->getController()->createUrl("pengumpulan"); ?>">
												<span class="link-text">Pengumpulan</span>
												<span class="link-desc">Unggah Berkas Laporan</span>
											</a>
										</span>
									</li>