protected/controllers/HomeController.php
<?php

class HomeController extends Controller
{
    /**
     * Declares class-based actions.
     */
    public function actions()
    {
        return array(
            // captcha action renders the CAPTCHA image displayed on the contact page
            'captcha'=>array(
                'class'=>'CCaptchaAction',
                'backColor'=>0xFFFFFF,
            ),
            // page action renders "static" pages stored under 'protected/views/site/pages'
            // They can be accessed via: index.php?r=site/page&view=FileName
            'page'=>array(
                'class'=>'CViewAction',
            ),
        );
    }

    /**
     * @return array action filters
     */
    public function filters()
    {
        return array(
            'accessControl', // perform access control for CRUD operations
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules()
    {
        return array(
            array('allow',
                'actions'=>array('login', 'logout', 'index', 'sync', 'error'),
                'users'=>array('*'),
            ),
            array('allow',
                'actions'=>array('index', 'error'),
                'users'=>array('@'),
            ),
            array('allow',
                'actions'=>array('admin', 'index', 'error'),
                'users'=>array('admin'),
            ),
            array('deny',  // deny all users
                'users'=>array('*'),
            ),
        );
    }

    /**
     * This is the default 'index' action that is invoked
     * when an action is not explicitly requested by users.
     */
//    public function actionIndex()
//    {
        // renders the view file 'protected/views/site/index.php'
        // using the default layout 'protected/views/layouts/main.php'
//        $this->render('index');
//    }

    /**
     * This is the action to handle external exceptions.
     */
    public function actionError()
    {
        if($error=Yii::app()->errorHandler->error)
        {
            if(Yii::app()->request->isAjaxRequest)
                echo $error['message'];
            else
                $this->render('error', $error);
        }
    }

    /**
     * Displays the contact page
     */
    public function actionContact()
    {
        $model=new ContactForm;
        if(isset($_POST['ContactForm']))
        {
            $model->attributes=$_POST['ContactForm'];
            if($model->validate())
            {
                $name='=?UTF-8?B?'.base64_encode($model->name).'?=';
                $subject='=?UTF-8?B?'.base64_encode($model->subject).'?=';
                $headers="From: $name <{$model->email}>\r\n".
                    "Reply-To: {$model->email}\r\n".
                    "MIME-Version: 1.0\r\n".
                    "Content-type: text/plain; charset=UTF-8";

                mail(Yii::app()->params['adminEmail'],$subject,$model->body,$headers);
                Yii::app()->user->setFlash('contact','Thank you for contacting us. We will respond to you as soon as possible.');
                $this->refresh();
            }
        }
        $this->render('contact',array('model'=>$model));
    }

    /**
     * Displays the login page
     */
    public function actionIndex()
    {
        $model=new LoginForm;

        // if it is ajax validation request
        if(isset($_POST['ajax']) && $_POST['ajax']==='login-form')
        {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }

        // collect user input data
        if(isset($_POST['LoginForm']))
        {
            $model->attributes=$_POST['LoginForm'];
            // validate user input and redirect to the previous page if valid
            if($model->validate() && $model->login())
                switch(Yii::app()->user->type)
                {
                    case -1 : $this->redirect(array("/tes"));                  break;
                    case 0  : $this->redirect(array("home/admin"));            break;
                    case 1  : $this->redirect(array("/pemodelan_siswa"));      break;
                    case 2  : $this->redirect(array("/pemodelan_mahasiswa"));  break;
                    case 3  : $this->redirect(array("/esai"));                 break;
                    case 4  : $this->redirect(array("/seminar_nasional"));     break;
                    default : $this->redirect(array("/"));
                }
        }
        // display the login form
        $this->render('login',array('model'=>$model));
    }

    /**
     * Show admin homepage.
     */
    public function actionAdmin()
    {
        $this->layout = 'main3';

        $criteria = array(
            'condition' => 'topic_id > 3 AND topic_id < 6',
        );
        $topic_school = Topic::model()->findAll($criteria);

        $topic_university = array();
        $criteria = array(
            'condition' => 'topic_id < 4',
        );
        $topics = Topic::model()->findAll($criteria);
        foreach($topics as $topic)
            array_push($topic_university, array(
                'topic' => $topic,
                'amount' => TopicChoice::model()->countByAttributes(array('topic_id' => $topic->topic_id)),
            ));

        $choosens_school = array();
        $criteria = array(
            'condition' => 'topic_id > 3 AND topic_id < 6',
            'order'     => 'contestant_id',
        );
        $topic_choice = TopicChoice::model()->findAll($criteria);
        foreach($topic_choice as $tc){
            $contestant = University::model()->findByPk($tc->contestant_id);
            $contestant = ($contestant == null) ? $contestant = Contestant::model()->findByPk($tc->contestant_id)->contestant_username : 'Tim ' . $contestant->contestant_team_name;
            array_push($choosens_school, array(
                'id' => $tc->contestant_id,
                'contestant' => $contestant,
                'topic' => Topic::model()->findByPk($tc->topic_id)->topic_title,
            ));
        }

        $choosens_university = array();
        $criteria = array(
            'condition' => 'topic_id < 4',
            'order'     => 'contestant_id',
        );
        $topic_choice = TopicChoice::model()->findAll($criteria);
        foreach($topic_choice as $tc){
            $contestant = University::model()->findByPk($tc->contestant_id);
            $contestant = ($contestant == null) ? $contestant = Contestant::model()->findByPk($tc->contestant_id)->contestant_username : 'Tim ' . $contestant->contestant_team_name;
            array_push($choosens_university, array(
                'id' => $tc->contestant_id,
                'contestant' => $contestant,
                'topic' => Topic::model()->findByPk($tc->topic_id)->topic_title,
            ));
        }

        $this->render('admin',array(
            'topic_school'        => $topic_school,
            'topic_university'    => $topic_university,
            'choosens_school'     => $choosens_school,
            'choosens_university' => $choosens_university,
        ));
    }

    /**
     * Generate School Contestant data for sync
     */
    public function actionSync()
    {
        $criteria = array(
            'condition' => 'contestant_type = 1 AND contestant_status = 2',
        );
        $model = Contestant::model()->findAll($criteria);
        $this->renderPartial('sync',array(
            'model'=>$model
        ));
    }

    /**
     * Logs out the current user and redirect to homepage.
     */
    public function actionLogout()
    {
        Yii::app()->user->logout();
        $this->redirect(Yii::app()->homeUrl);
    }
}

protected/controllers/TesController.php
<?php

class TesController extends Controller
{
    /**
     * @var string the default layout for the views. Defaults to '//layouts/main4', meaning
     * using two-column layout. See 'protected/views/layouts/main4.php'.
     */
    public $layout='//layouts/main4';

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules()
    {
        return array(
            array('allow',
                'actions'=>array('topik', 'penyisihan', 'index'),
                'users'=>array('@'),
            ),
            array('deny',  // deny all users
                'users'=>array('*'),
            ),
        );
    }

    /**
     * Index
     */
    public function actionIndex()
    {
        if(Yii::app()->user->id > 50) $this->render('preliminary1');
        else $this->render('index');
    }

    public function actionPenyisihan()
    {
        if($_POST != null) {
            $this->render('preliminary2', array(
                'start' => 11,
            ));
        }
        else {
            $this->render('preliminary2', array(
                'start' => 1,
            ));
        }
    }

    public function actionTopik()
    {
        $choice = TopicChoice::model()->find(array(
            'condition'=>'contestant_id=:id',
            'params'=>array(':id'=>Yii::app()->user->id),
        ));
        $criteria = array(
            'condition' => 'topic_id > 3 AND topic_id < 6',
        );
        $topics = Topic::model()->findAll($criteria);

        $this->render('topic', array(
            'topics'=>$topics,
            'choice'=>$choice,
        ));
    }

    /**
     * Upload Motivation Letter
     */
    public function actionMotivation_letter()
    {
        if( (!Yii::app()->user->isGuest) && (Yii::app()->user->type==-1))
        {
            if(!empty($_FILES)){
                Yii::app()->user->setFlash('warning', 'Laman ini hanya untuk uji coba. Berkas yang Anda unggah tidak akan disimpan');
            }
            $this->render('letter');
        }
        else throw new CHttpException(404,'The requested page does not exist.');
    }

    /**
     * Show University Modeling Contestant Problem upload page
     */
    public function actionMasalah()
    {
        $model = Topic::model()->findAll();
        $this->render('problem', array(
            'model'=>$model,
        ));
    }

    public function actionPengumpulan()
    {
        if( (!Yii::app()->user->isGuest) && (Yii::app()->user->type==-1))
        {
            $topic_choice = TopicChoice::model()->findByAttributes(array('contestant_id'=>Yii::app()->user->id));
            if($topic_choice == null) $topic = new Topic();
            else $topic = Topic::model()->findByPk($topic_choice->topic_id);

            //$filename = Contestant::model()->findByPk(Yii::app()->user->id)->contestant_username.'_'.$topic_choice->topic_id.'_Laporan.pdf';
            $filename = "";
            $model = Problem::model()->findByAttributes(array('contestant_id' => Yii::app()->user->id));
            if($model == null){
                $model                = new Problem();
                $model->contestant_id = Yii::app()->user->id;
            }

            if(!empty($_FILES)){
                if((strlen($filename)!=0) && (file_exists('upload/'.$filename))) unlink('upload/'.$filename);
                else $model->file_name = $filename;
                move_uploaded_file($_FILES['file']['tmp_name'], 'upload/'.$filename);
                if((strlen($filename)!=0) && (file_exists('backup/'.$filename))) unlink('backup/'.$filename);
                copy('upload/'.$filename, 'backup/'.$filename);
                if($model->save()) Yii::app()->user->setFlash('success', 'Berkas berhasil diunggah dengan nama '.$filename);
            }

            $this->render('submit', array(
                'problem' => $topic,
                'model'  => $model,
            ));
        }
        else throw new CHttpException(404,'The requested page does not exist.');
    }
}

protected/controllers/TopicController.php
<?php

class TopicController extends Controller
{
    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules()
    {
        return array(
            array('allow',
                'actions'=>array('choose', 'index'),
                'users'=>array('@'),
            ),
            array('allow',
                'actions'=>array('edit', 'choose', 'delete', 'index'),
                'users'=>array('admin'),
            ),
            array('deny',  // deny all users
                'users'=>array('*'),
            ),
        );
    }

    /**
     * Edit the topic
     */
    public function actionEdit()
    {
        $model = Topic::model()->findByPk($_GET['id']);
        if(isset($_POST['Topic']))
        {
            $model->attributes = $_POST['Topic'];
            if($model->validate()) $model->update();
        }
        $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('home/admin'));
    }

    /**
     * Choose the topic
     */
    public function actionChoose()
    {
        $model = new TopicChoice();
        if(isset($_POST['choice']))
        {
            $choosen = TopicChoice::model()->countByAttributes(array('topic_id' => $_POST['choice']));
            /*$quota = Topic::model()->find(array(
                'condition'=>'topic_id=:id',
                'params'=>array(':id'=>$_POST['choice']),
            ))->topic_quota;*/
            $quota = $choosen + 1;
            if($quota > $choosen){
                $model->topic_id = $_POST['choice'];
                if(isset($_POST['username'])){
                    $temp = Contestant::model()->find(array(
                        'condition'=>'contestant_username=:username',
                        'params'=>array(':username'=>$_POST['username']),
                    ));
                    if($temp != null) $model->contestant_id = $temp->contestant_id;
                    else $this->redirect(array('home/admin'));
                }
                else $model->contestant_id = $_POST['id'];
                $exist_model = TopicChoice::model()->find(array(
                    'condition'=>'contestant_id=:contestant_id',
                    'params'=>array(':contestant_id'=>$model->contestant_id,),
                ));
                if($exist_model!=null) $this->redirect(array('home/admin?choosen=true'));
                if(($exist_model==null) && $model->validate()) $model->save();
            }
        }
        $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('home/admin'));
    }

    /**
     * Delete TopicChoice
     */
    public function actionDelete()
    {
        TopicChoice::model()->deleteAll( 'contestant_id=:id', array(':id'=>$_GET['id']) );
        $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('home/admin'));
    }

    /*    public function actionDummy()
    {
        for($i=1;$i<101;++$i){
            $model = new Contestant();
            $model->contestant_id = $i;
            $ID = $i;
            while(strlen($ID)<3) $ID='0'.$ID;
            $model->contestant_username = 'tes'.$ID;
            $user = new UserIdentity('admin', '');
            $model->contestant_password = $user->encrypt('tes');
            $model->contestant_type = -1;
            $model->contestant_status = 2;
            $model->save();
        }
        echo 'Success';
    }
*/
}

protected/views/tes/index.php
<?php
/* @var $this UniversityController */
$id = Yii::app()->user->id;
switch($id){
case 7   : $name = 'James Bond'; break;
case 8   : $name = 'Saras 008';  break;
case 21  : $name = 'Jakarta';    break;
case 22  : $name = 'Bandung';    break;
default  : $name = Contestant::model()->findByPk($id)->contestant_username;
}
?>
	<ul class="contestant-announcement">
		<h4>Selamat Datang <?php echo $name; ?></h4>
		<?php if(Yii::app()->user->status == 2): ?>
		<li>
			Setiap Laporan Pemodelan yang dikumpulkan harus mencantumkan <i>Statement of Originality</i>. Contoh <i>Statement of Originality</i> dapat diunduh di <a href="<?php echo Yii::app()->baseUrl.'/berkas/STATEMENT OF ORIGINALITY.doc'; ?>" target="_blank">tautan ini</a> 
		</li>
		<li>
			Selamat! Tim Anda sudah resmi terdaftar sebagai peserta Kompetisi Pemodelan Matematika tingkat Mahasiswa MCF - MMC ITB 2014!
			Terima kasih atas partisipasinya, sampai berjumpa di periode pemodelan pada tanggal <?php echo Yii::app()->params['university']['semifinal']['begin'].' - '.Yii::app()->params['university']['semifinal']['end']; ?>!
		</li>
		<?php endif; ?>
		<li>
			Silahkan melengkapi <a href="">Data Profil</a> dan mengunggah <a href="<?php echo Yii::app()->controller->createUrl('motivation_letter'); ?>" style="font-style: italic;">Motivation Letter</a> dengan menekan menu yang telah disediakan.<br>
			Jika sampai tanggal <?php echo date("d M Y", strtotime(Contestant::model()->findByPk($id)->contestant_expired_registration_date)) ?> persyaratan masih belum lengkap, Tim Anda akan dianggap  mengundurkan diri dan uang pendaftaran tidak dapat dikembalikan. 
		</li>
	</ul>

protected/views/tes/letter.php
<?php
/* @var $this UniversityController */
/* @var $model University */

$new   = true;
$admin = (!$new && Yii::app()->user->type==0);
?>

<div class="form-error-message alert alert-danger"></div>


<?php if (Yii::app()->user->hasFlash('warning')) : ?>
<div class="alert alert-warning letter-success"><?php echo Yii::app()->user->getFlash('warning'); ?></div>
<form enctype="multipart/form-data" class="form-horizontal" action="<?php echo $this->action->id; ?>" method="post" role="form" style="margin: 0 0 50px 75px;">
<?php else: ?>
<form enctype="multipart/form-data" class="form-horizontal" action="<?php echo $this->action->id; ?>" method="post" role="form" style="margin: 52px 0 50px 75px;">
<?php endif; ?>
	<div class="form-group">
		<label class="control-label col-md-2" for="University_contestant_motivation_letter">Kumpulkan <i>Motivation Letter</i></label>
		<div class="col-md-5">
			<?php $file = ((!$new) && ($model->contestant_motivation_letter != '')) ? 'fileinput-exists' : 'fileinput-new'; ?>
			<div class="fileinput <?php echo $file; ?>" data-provides="fileinput">
				<div class="input-group">
					<div class="form-control uneditable-input span3" data-trigger="fileinput" style="width: 360px;">
						<i class="glyphicon glyphicon-file fileinput-exists"></i>
						<span class="fileinput-filename"><?php echo ($file=='fileinput-exists') ? $model->contestant_motivation_letter : ''; ?></span>
					</div>
					<span class="input-group-addon btn btn-default btn-file">
						<span class="fileinput-new">Pilih Berkas</span>
						<span class="fileinput-exists">Ubah</span>
						<input type="file" name="file">
					</span>
					<a href="#" class="input-group-addon btn btn-default fileinput-exists" data-dismiss="fileinput">Hapus</a>
				</div>
			</div>
		</div>
	</div>
	<div class="form-group">
		<label class="control-label col-md-2" for="University_contestant_motivation_letter"></label>
		<div class="col-md-6">
			<input class="btn btn-success" type="submit" value="Kumpulkan">
		</div>
	</div>
</form>
<script language="javascript" type="text/javascript">
var size = 10 * 1024 * 1024;
jQuery('.form-error-message').hide();
jQuery('input[type=submit]').click(function(){
	var error = '';
	jQuery('form').css('margin-top', '52px');
	jQuery('.has-error').removeClass('has-error');
	jQuery('.form-error-message').hide();
	if((file = jQuery('input[name=file]')[0].files[0]) != null){
		if(file.size > size){
			error = 'Ukuran Berkas terlalu besar (maksimal 10MB)';
		}
		else if(file.type != 'application/pdf'){
			error = 'Berkas yang diunggah harus berformat pdf';
		}
	}
	else return false;
	if(error != ''){
		jQuery('form').css('margin-top', '0');
		jQuery('.form-error-message').html(error);
		jQuery('.form-error-message').css('display','inline-block');
		window.scrollTo(0,0);
		return false;
	}
});
</script>

protected/views/tes/preliminary1.php
<div style="margin: 30px 0 0 400px;">
<div>Apakah Anda yakin untuk memasuki sistem penyisihan?</div>
<div>
	<div style="font-size: 10px;"><strong>Anda hanya diberikan waktu 2 jam untuk mengerjakan terhitung</strong></div>
	<div style="font-size: 10px;"><strong>dari Anda menekan tombol Lanjutkan</strong></div>
</div>
<div style="margin-top: 50px;">
	<a href="<?php echo Yii::app()->createUrl("/home/logout"); ?>" style="margin-left: 30px;"><button class="btn btn-danger" style="width: 100px;">Batal</button></a>
	<a href="<?php echo Yii::app()->createUrl("/tes/penyisihan"); ?>" style="margin-left: 70px;"><button class="btn btn-success" style="width: 100px;">Lanjutkan</button></a>
</div>
</div>

protected/views/tes/preliminary2.php
<?php
$form=$this->beginWidget('CActiveForm', array(
        'id' => 'preliminary-form',
        'enableClientValidation' => true,
        'clientOptions' => array(
            'validateOnSubmit' => true,
        ),
        'htmlOptions' => array(
        	'class'=>'form-horizontal',
	        'role'=>'form',
	        'style'=>'margin: 0 0 50px 75px',
	        'enctype'=>'multipart/form-data',
        )
    )); 
?>

<?php //echo $form->errorSummary($model); ?>

<!-- <form enctype="multipart/form-data" class="form-horizontal" action="<?php echo $this->action->id; ?>" method="post" role="form" style="margin: 0 0 50px 75px;"> -->

	<?php for($i = $start; $i<($start+10) ; ++$i) { ?>
	<div style="margin-bottom: 50px;">
		<div style="margin-top: -30px; position: relative; top: 27px;"><?php echo $i; ?></div>
		<div style="margin-left: 30px;">
			<img src="<?php echo Yii::app()->request->baseUrl; ?>/img/soal.jpg" border="1px bold line">
			<div style="margin-left: 10px;">
				<label class="radio-inline" style="width: 15%;">
					<input type="radio" name="Pilihan<?php echo $i; ?>" value="A"> A. pil A
				</label>
				<label class="radio-inline" style="width: 15%;">
					<input type="radio" name="Pilihan<?php echo $i; ?>" value="B"> B. pil B
				</label>
				<label class="radio-inline" style="width: 15%;">
					<input type="radio" name="Pilihan<?php echo $i; ?>" value="C"> C. pil C
				</label>
				<label class="radio-inline" style="width: 15%;">
					<input type="radio" name="Pilihan<?php echo $i; ?>" value="D"> D. pil D
				</label>
				<label class="radio-inline" style="width: 15%;">
					<input type="radio" name="Pilihan<?php echo $i; ?>" value="E"> E. pil E
				</label>
			</div>
		</div>
	</div>
	<?php } ?>
	<input type="submit" class="btn btn-success" value="Kumpulkan" style="margin-left: 40px;">
<!-- </form> -->

<?php $this->endWidget(); ?>

<script language="javascript" type="text/javascript">

</script>

protected/views/tes/problem.php
<?php
/* @var $this UniversityController */
/* @var $model Topic*/
?>

<div style="margin-left: 75px;">
	<div>Berikut adalah pilihan topik masalah yang akan dilombakan</div>
	<?php
	$i = 1;
	foreach($model as $mdl){
	?>
		<div class="desc-list">
			<span class="col-md-1">Topik <?php echo $i; ?></span>
			<span>: <a class="label label-info" href="<?php echo $mdl->topic_source; ?>" target="_blank"><?php echo $mdl->topic_title; ?></a></span>
		</div>
	<?php
	++$i;
	}
	?>
	<div style="margin-top:50px;">Silahkan memilihnya di menu <a href="<?php echo Yii::app()->createUrl('tes/topik'); ?>">Topik</a></div>
</div>

protected/views/tes/submit.php
<?php
$new   = ($model->file_name == '');
$admin = (!$new && Yii::app()->user->type==0);
?>

<div class="form-error-message alert alert-danger"></div>

<?php if (Yii::app()->user->hasFlash('success')) : ?>
<div class="alert alert-success letter-success"><?php echo Yii::app()->user->getFlash('success'); ?></div>
<form enctype="multipart/form-data" class="form-horizontal" action="<?php echo $this->action->id; ?>" method="post" role="form" style="margin: 0 0 50px 75px;">
<?php else: ?>
<form enctype="multipart/form-data" class="form-horizontal" action="<?php echo $this->action->id; ?>" method="post" role="form" style="margin: 52px 0 50px 75px;">
<?php endif; ?>
	<div class="form-group">
		<label class="control-label col-md-2"  for="University_contestant_problem">Permasalahan</label>
		<span style="position: relative; top: 5px;">
			<span class="<?php echo ($problem->topic_id == 3)?'col-md-6':'col-md-4'; ?>" style="position: relative; top: 5px;">: <?php echo $problem->topic_title; ?></span>
			<span><a class="label label-info" target="_blank" href="https://docs.google.com/file/d/<?php echo $problem->topic_source; ?>/preview">Lihat</a></span>
			<span><a class="label label-success" target="_blank" href="https://docs.google.com/uc?export=download&id=<?php echo $problem->topic_source; ?>">Unduh</a></span>
			<?php if($problem->topic_id == 3) : ?>
				<span><a class="label label-warning" target="_blank" href="https://docs.google.com/uc?export=download&id=0By_WcqkJZeCgSThpQVI5a0VLY1k">Unduh Data Set</a></span>
			<?php endif; ?>
		</span>
	</div>
	<div class="form-group">
		<label class="control-label col-md-2" for="University_contestant_problem">Kumpulkan Berkas</label>
		<span style="position: relative; float: left; top: 5px; left: 15px; margin-right: 5px;"> : </span>
		<span class="col-md-5">
			<?php $file = ((!$new) && ($model->file_name != '')) ? 'fileinput-exists' : 'fileinput-new'; ?>
			<div class="fileinput <?php echo $file; ?>" data-provides="fileinput">
				<div class="input-group">
					<div class="form-control uneditable-input span3" data-trigger="fileinput" style="width: 360px;">
						<i class="glyphicon glyphicon-file fileinput-exists"></i>
						<span class="fileinput-filename"><?php echo ($file=='fileinput-exists') ? $model->file_name : ''; ?></span>
					</div>
					<span class="input-group-addon btn btn-default btn-file">
						<span class="fileinput-new">Pilih Berkas</span>
						<span class="fileinput-exists">Ubah</span>
						<input type="file" name="file">
					</span>
					<a href="#" class="input-group-addon btn btn-default fileinput-exists" data-dismiss="fileinput">Hapus</a>
				</div>
			</div>
		</span>
	</div>
	<div class="form-group">
		<label class="control-label col-md-2" for="University_contestant_problem"></label>
		<div class="col-md-6" style="margin-left: 7px;">
			<input class="btn btn-success" type="submit" value="Kumpulkan">
		</div>
	</div>
</form>
<script language="javascript" type="text/javascript">
var size = 10 * 1024 * 1024;
jQuery('.form-error-message').hide();
jQuery('input[type=submit]').click(function(){
	var error = '';
	jQuery('form').css('margin-top', '52px');
	jQuery('.has-error').removeClass('has-error');
	jQuery('.form-error-message').hide();
	if((file = jQuery('input[name=file]')[0].files[0]) != null){
		if(file.size > size){
			error = 'Ukuran Berkas terlalu besar (maksimal 10MB)';
		}
		else if(file.type != 'application/pdf'){
			error = 'Berkas yang diunggah harus berformat pdf';
		}
	}
	else return false;
	if(error != ''){
		jQuery('.letter-success').remove();
		jQuery('form').css('margin-top', '0');
		jQuery('.form-error-message').html(error);
		jQuery('.form-error-message').css('display','inline-block');
		window.scrollTo(0,0);
		return false;
	}
});
</script>

protected/views/tes/topic.php
<?php
/* @var $this HomeController */
?>
<div style="margin-left: 75px;">
	<form class="form-horizontal" action="<?php echo Yii::app()->createUrl('topic/choose'); ?>" method="post" role="form">
		<input type="hidden" name="returnUrl" value="<?php echo Yii::app()->createUrl('tes/topik'); ?>">
		<input type="hidden" name="id" value="<?php echo Yii::app()->user->id; ?>">
		<div class="form-group">
			<label class="control-label col-md-2">Pilihan Topik</label>
			<span class="col-md-4">
				<select class="form-control" <?php echo ($choice==null)?'':'disabled '; ?>name="choice">
					<?php
					foreach($topics as $topic){
						$choosen   = (($choice!=null)&&($topic->topic_id==$choice->topic_id))?' selected':'';
						echo '<option value="'.$topic->topic_id.'"'.$choosen.'>'.$topic->topic_title.'</option>';
					}
					?>
				<select>
			</span>
			<?php if($choice==null) {?><input id="choice-button" class="btn btn-default col-md-1" type="submit" value="Pilih"> <?php } ?>
		</div>
	</form>
</div>

<script type="application/javascript">
jQuery(function() {
    jQuery('#choice-button').click(function() {
        return confirm('Apakah Anda yakin? Pilihan tidak dapat diganti');
    });
});
</script>